debug: false
uuid: 85a662e8-d45c-48d7-b355-e29aed888c5d
token_id: jgsUxTJVDsjdPr0W
token: HoOWnLC2hZkbQRi8rQg29wgIm4ulbo0NJZ8nY1V63NfForupKw9VLMvLEc5FM36l
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/fullchain.pem
    key: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.kswarrior.qzz.io'
