debug: false
uuid: 36b13e9e-c688-47b2-97b5-ec7e326e139c
token_id: 2d87B2i4yzsptrWy
token: nIeolDAelYkRlk0QlIIGIpy659eyU3l9Tf0ZfS8lBb5KZ610h31CKtXYHNzwTypa
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/fullchain.pem
    key: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.kswarrior.qzz.io'
