version: '3.8'

services:
  ks-pterodactyl-wings-vm:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings-vm
    restart: unless-stopped
    environment:
      TZ: "$TIMEZONE"
    command: >
      bash -c "
      echo '🚀 Starting Wings in VM mode...' &&
      wings"
    networks:
      - ptero-net
    ports:
      - "8080:8080"     # Example HTTP port
      - "2022:2022"     # Example SSH or SFTP port
      - "443:443"     # Example Wings internal port
    volumes:
      - ./config:/etc/pterodactyl  # Data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ptero-net:
    driver: bridge
